### ISSUE TITLE
Unable to select project

### ISSUE THREAD

**Issue by jesse-windebank** [michal-kapala/jitterbit-extractor#1]
Thanks for putting this together.

Nothing happens when I browse for a Jitterbit project folder. Please take a look at the video [here](https://drive.google.com/file/d/1nRQlDrGh9GTyGGTEYqEmdrUmNXo6b43C/view?usp=sharing), which shows the issue.

**Comment by michal-kapala** [comment]
You're using macOS here, so I'd assume the project path is just unsupported right now. I've built this with Windows in mind as the target platform (the paths use `\` rather than `/` as separators) which is my guess for the issue. You can make sure by creating a log, run the app with `stderr` directed to `stdout`, I believe this should work on Mac too:
```
./JitterbitExtractor > log.txt 2>&1
```

**Comment by michal-kapala** [comment]
@jessewindebank1809 please pull 07f61d1 and rebuild, hopefully it enables macOS support

**Comment by jesse-windebank** [comment]
All fixed thanks for the update @michal-kapala
